version: '3.4'

services:
  eventpad_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_eventpad_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  eventpad_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_eventpad_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq
    
  eventpad_redis:
    ports:
      - "6379:6379"
    networks:
      - shared_eventpad_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  eventpad_api:
    ports:
      - "10000:8080"
    networks:
      - shared_eventpad_net
    env_file:
      - env.api

  eventpad_pay:
    ports:
      - "10001:8080"
    networks:
      - shared_eventpad_net
    env_file:
      - env.pay

  eventpad_worker:
    networks:
      - shared_eventpad_net
    ports:
      - "10002:8080"
    env_file:
      - env.worker


networks:
  shared_eventpad_net:
    name: event_pad
    driver: bridge