version: '3.4'

services:
  eventpad_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "35432:5432"
    networks:
      - shared_eventpad_net
    volumes:      
      - .docker/postgresql/data/:/var/lib/postgresql/data

  eventpad_rabbitmq:
    ports:
      - "35672:5672"
      - "35673:5673"
      - "45672:15672" 
    networks:
      - shared_eventpad_net
    volumes:      
      - .docker/rabbitmq:/var/lib/rabbitmq
    
  eventpad_redis:
    ports:
      - "36379:6379"
    networks:
      - shared_eventpad_net
    volumes:      
      - .docker/redis/data/:/data

  eventpad_api:
    ports:
      - "10000:8080"
    networks:
      - shared_eventpad_net
    restart: on-failure
    volumes:      
      - .docker/api/keys:/app/keys 
      - .docker/api/wwwroot/Files:/app/wwwroot/Files
    env_file:
      - env.api

  eventpad_pay:
    ports:
      - "10001:8080"
    networks:
      - shared_eventpad_net
    restart: on-failure
    env_file:
      - env.pay

  eventpad_worker:
    networks:
      - shared_eventpad_net
    restart: on-failure
    ports:
      - "10002:8080"
    env_file:
      - env.worker

  eventpad_web:
    networks:
      - shared_eventpad_net
    restart: on-failure
    ports:
      - "10003:80"

networks:
  shared_eventpad_net:
    name: event_pad
    driver: bridge